-- ============================================================================
-- 010_drop_compat.sql — SIN EFECTO, se conserva por orden de numeración.
--
-- Iba a retirar las vistas instruments_v2, instrument_flows_v2 e
-- instrument_flows_v3 que dejaba el 009. Nunca llegaron a existir: el 009 se
-- corrió sin la parte que las creaba, y por eso el front tiró
-- "Could not find the table public.instruments_v2" hasta que se deployó el
-- código nuevo.
--
-- La limpieza que sí correspondía está en 016_limpieza_final.sql.
-- ============================================================================
